# Generated by Django 4.2 on 2023-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MotionSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('motion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UltrasonicSensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=10)),
            ],
        ),
    ]
