# Generated by Django 4.2 on 2023-05-18 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_medicaldispensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('dispId', models.IntegerField(default=1)),
                ('medicine', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='medicaldispensor',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
