# Generated by Django 4.2 on 2023-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=100)),
                ('alcohol', models.BooleanField(default=False)),
                ('pregnant', models.CharField(max_length=1)),
                ('rx_otc', models.CharField(max_length=50)),
            ],
        ),
    ]
